server:
  port: 8080
# 打印sql
logging:
  level:
    org.wlgzs.agricultural_share.dao: DEBUG
#logging:
#  config: classpath:logback-spring.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xf_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 2016wlgzs
    driver-class-name: com.mysql.jdbc.Driver
    platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
        cache: false
        mode: HTML5
        encoding: UTF-8
        prefix: classpath:/templates/
        suffix: .html
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

